Controllers/BarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JeeBerryHome3.Controllers
{
    public class BarsController : Controller
    {
        //
        // GET: /Bars/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Neo4jClient;
using Neo4jClient.Cypher;
using JeeBerryHome3.Models;

namespace JeeBerryHome3.Controllers
{
    public class UsersController : Controller
    {
        //
        // GET: /Users/

        public ActionResult Index()
        {
            return View();
        }

        public void GetUserData(String ime, String prezime /*itd*/)
        {
            //sliku moras ovde, samo da ti prekopitam kod
            //sad mozes sve sem slike
        }

        public void SaveUserData(String ime, String prezime, String korisnickoIme, String sifra, String slikaUrl)
        {
            
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - FADRUM</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <style>
            p.site-title a {
                color: black;
            }
        </style>

    </head>
    <body style="background-color:#D0CEE7">
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">
                        <a href="@Url.Action("Index","Home")">
                            <img src="~/Content/Liver.png" />
                        </a>
                    </p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Početna", "Index", "Home")</li>                            
                            <li>@Html.ActionLink("Kafane","Index", "Bars")</li>
                            <li>@Html.ActionLink("Bendovi", "Index", "Bends")</li>
                            <li>@Html.ActionLink("Profil", "Index", "UserProfile")</li>
                            <li>@Html.ActionLink("Stavke menija", "Index", "MenuItems")</li> 
                            <li>@Html.ActionLink("Korisnici", "Index", "Users")</li>                      
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body" style="background-color:#635CB8">
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer style="background-color:#D0CEE7">
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - JeeBerry Application</p>
                </div>
            </div>
        </footer>        
                @Scripts.Render("~/bundles/jquery")
                <script src="~/Scripts/jquery-1.11.2.js"></script>
                <script src="~/Scripts/bootstrap.min.js"></script>       

        @RenderSection("scripts", required: false)
    </body>
</html>